# Rakefile
require 'spec/rake/spectask'
require 'rake/clean'
require 'yaml'

CLOBBER.include FileList['*.war']
CLEAN.include FileList['tmp']

desc "Build war archive"
task :build do
  cmd = "rave war"
  cmd = "jruby -S #{cmd}" if RUBY_PLATFORM == 'java'
  system cmd
end

desc "Deploy as robot (requires appspot account)"
task :deploy => :build do
  system "c:/appengine-java-sdk/bin/appcfg update tmp/war"
end

Spec::Rake::SpecTask.new do |t|
  t.spec_files = FileList['spec/**/*_spec.rb']
end

task :test => :spec
